import numpy as np
import matplotlib.pyplot as plt
import random
import json
import glob




coords = [
        [69 ,63],
        [3 ,35],
        [71 ,79],
        [1 ,47],
        [11 ,15],
        [87 ,23],
        [37 ,33],
        [87 ,29],
        [35 ,81],
        [55 ,71],
        [41 ,51],
        [93 ,9],
        [11 ,49],
        [75 ,89],
        [75 ,69],
        [97 ,95],
        [15 ,13],
        [63 ,95],
        [47 ,41],
        [45 ,41],
        [89 ,43],
        [45 ,59],
        [95 ,23],
        [19 ,83],
        [71 ,69],
        [27 ,19],
        [17 ,57],
        [93 ,15],
        [59 ,29],
        [35 ,39],
        [33 ,51],
        [61 ,21],
        [89 ,53],
        [33 ,85],
        [37 ,37],
        [21 ,91],
        [67 ,95],
        [61 ,15]
]

#tourFiles = glob.glob("../output/*.json")
#print(tourFiles)
#exit()

tours = [
    # A very nice and very short giant tour, generated by our ACO + 2opt(?)
    # [0,0,0,0,0,9,8,33,35,23,21,10,30,26,12,3,1,4,16,25,6,29,34,19,18,28,31,37,11,27,22,5,7,20,32,15,13,36,17,2,14,24,0]

    # A good one
    #[0,30,29,34,19,18,10,0],[0,21,6,25,16,4,1,3,12,26,0],[0,23,35,33,8,9,2,14,0],[0,24,17,36,13,15,32,20,7,0],[0,5,22,27,11,37,31,28,0]

    # After Bugfixes /w Tobi
    #[0,9,17,36,13,15,32,20,0],[0,7,5,22,27,11,37,0],[0,31,28,18,19,29,34,6,0],[0,25,16,4,1,3,12,26,30,10,0],[0,21,23,35,33,8,2,24,14,0],


    # CURRENT_BEST @ 742
    [0,24,2,17,36,13,15,32,20,7,0], [0,5,22,27,11,37,31,28,0],[0,25,16,4,1,3,12,26,30,10,0],[0,21,29,34,6,19,18,0],[0,8,33,35,23,9,14,0],

    #[0,37, 11, 27, 22, 5, 7,0],[0,10,30,29,34,19,18,0],[0,20,32,15,13,36,17,2,14,0],[0,28,31,6,25,16,4,1,3,12,26,21,0],[0,24,33,35,23,8,9,0]


]
def plotour(tours,coords):
    coordX = []
    coordY = []
    for node in coords:
        coordX.append(node[0])
        coordY.append(node[1])


    toursX = []
    toursY = []
    for tour in tours:
        print("LenaTOurs")
        print(tour)
        tourNodesX = []
        tourNodesY = []

        for node in tour:
            tourNodesX.append(coords[node][0])
            tourNodesY.append(coords[node][1])

        toursX.append(tourNodesX)
        toursY.append(tourNodesY)



    fig, ax = plt.subplots(figsize=(5, 5))
    ax.scatter(coords[0][0], coords[0][1], s=200, color='green', label="Depot")

    for x in range(1, len(coords)):
        ax.scatter(coords[x][0],coords[x][1], color="gold")
        ax.annotate(str("#" + str(x)), (coords[x][0],coords[x][1]))

    # Print out Informations about the routes into the console;
    for tour in tours: 
        print(tour)


    for i in range(len(toursX)):
        print("#" + str(i) + str(toursX[i]) + "/" + str(toursY[i]))
        ax.plot(toursX[i], toursY[i], color=np.random.rand(3,), label="Tour #" + str(i))


    ax.set_xlabel("x")
    ax.set_ylabel("y")
    ax.grid(True)
    ax.legend(loc = 'best')

    plt.show()


plotour(tours,coords)